all: doc

doc: pdf html

pdf:
#	mddia -pdf notes.md | pandoc --bibliography ./Project.bib --csl=harvard-imperial-college-london.xml -o notes.pdf
	mddia -pdf report.md | pandoc --toc --number-sections --bibliography ./Project.bib --csl=harvard-imperial-college-london.xml -o report.pdf


html:
#	mddia notes.md | pandoc --bibliography ./Project.bib --csl=harvard-imperial-college-london.xml -o notes.html
#    mddia report.md | pandoc --bibliography ./Project.bib --csl=harvard-imperial-college-london.xml -o report.html

